# Generated by Django 2.0 on 2018-10-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
