# Generated by Django 2.0 on 2018-10-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181001_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='deleted',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='updated',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='deleted',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
