# Generated by Django 2.0 on 2018-10-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181001_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='deleted',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='computer',
            name='updated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='site',
            name='deleted',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(default=None),
        ),
    ]
